version: '3.8'

networks:
  db_network:
    driver: bridge

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./scripts/create-db.sql:/docker-entrypoint-initdb.d/create-db.sql
    networks:
      - db_network
volumes:
  db:
    driver: local